version: '3.9'

services:

    nginx:
        image: nginx:latest        
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "25746:80"
        depends_on:
            - backend
            - mongo

    # frontend:
    #     build: 
    #         context: ./frontend
    #         args:
    #             - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}

    backend:
        build: ./backend/
        env_file: ./config/.env
        depends_on:
            - mongo

    worker:
        build: ./src/
        env_file: ./config/.env
        depends_on:
            - mongo

    mongo:
        image: mongo
        env_file: ./config/.env