version: '3.9'

services:

    nginx:
        image: nginx:latest        
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "25746:80"
        depends_on:
            - backend
            - mongo

    # frontend:
    #     build: 
    #         context: ./frontend
    #         args:
    #             - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}

    backend:
        build: ./backend/
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - FETCH_INTERVAL=${FETCH_INTERVAL}
        depends_on:
            - mongo

    worker:
        build: ./src/
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - FETCH_INTERVAL=${FETCH_INTERVAL}
        depends_on:
            - mongo

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}