version: '3.9'

services:

    nginx:
        image: nginx:latest        
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "23879:80"

    # frontend:
    #     build: 
    #         context: ./frontend
    #         args:
    #             - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}

    # backend:
    #     build: ./backend/
    #     env_file: ./config/.env

    worker:
        build: ./src/
        env_file: ./config/.env

    redis:
        image: redis:alpine
